### ISSUE TITLE
iser mount logic for bigflash

### ISSUE THREAD

**Issue by csirving** [sdsc/gordon#1]
The check if the iser drive is mounted doesn't work on bigflash nodes since their device is /dev/md1 not /dev/sdb.  It could be fixed simply by checking that /scratch is in the mtab, otherwise an if statement is needed.

**Comment by rpwagner** [comment]
Can you write a patch? Also, these files need to be migrated to gordon-config roll under the sdsc org.

**Comment by tcooper** [comment]
Closing... repository is deprecated.
